/*
	ΕΛΠΙΣ DNS - network map

	South East Asia with the four networks on it. The land comes from
	img/sea-map.json (generated by tools/make-sea-map.py); the networks,
	their endpoints and the cities they reach come from network.json, so
	adding a network is a JSON edit like everything else on this site.

	How it is put together:

	  - The land is drawn once, in map units, inside one <g> that is
	    moved and scaled as a whole. Panning and zooming is a transform
	    change, nothing is redrawn.
	  - The nodes, cities and links sit in a second layer drawn in screen
	    pixels and are repositioned on every view change, so a node is
	    the same size at every zoom and its label never grows.
	  - Nodes closer together than a finger's width are fanned out into
	    a short column with a leader line back to where they really are.
	    Zoom in and they separate on their own.

	Interaction: drag to pan, Ctrl or Cmd with the wheel to zoom (a plain
	wheel still scrolls the page), double-click to zoom in, the buttons
	for everything else. Every node is focusable, and the cards under
	the map carry the same information as the tooltips.
*/

(function(){

	const NS = "http://www.w3.org/2000/svg";

	const card = document.getElementById("map");
	const grid = document.getElementById("net-grid");

	if(!card) return;

	const reducedMotion =
		window.matchMedia("(prefers-reduced-motion: reduce)").matches;

	const MAX_ZOOM = 14;
	const CLUSTER_PX = 24;
	const NEAREST = 2;

	let land = null;
	let net = null;

	let svg, world, overlay, tip;
	let width = 0;
	let height = 0;

	// screen = map * k + t
	const view = { k: 1, tx: 0, ty: 0 };

	let minZoom = .2;
	let touched = false;
	let pinned = null;
	let animation = null;

	/* ---------- projection ---------- */

	function merc(lat){

		const rad = Math.max(-85, Math.min(85, lat)) * Math.PI / 180;

		return Math.log(Math.tan(Math.PI / 4 + rad / 2)) * 180 / Math.PI;
	}

	// Has to match project() in tools/make-sea-map.py.
	function project(lon, lat){

		const [west, , , north] = land.bbox;

		return [
			(lon - west) * land.scale,
			(merc(north) - merc(lat)) * land.scale
		];
	}

	function toScreen([x, y]){
		return [x * view.k + view.tx, y * view.k + view.ty];
	}

	/* ---------- the view ---------- */

	function fit(box){

		const [x0, y1] = project(box[0], box[1]);
		const [x1, y0] = project(box[2], box[3]);

		const k = Math.min(width / (x1 - x0), height / (y1 - y0));

		return clamp({
			k,
			tx: width / 2 - k * (x0 + x1) / 2,
			ty: height / 2 - k * (y0 + y1) / 2
		});
	}

	// Never zoom out past the edge of the data, never pan off it.
	function clamp(v){

		const k = Math.max(minZoom, Math.min(MAX_ZOOM, v.k));

		const span = (size, extent, t) => {

			const scaled = extent * k;

			if(scaled <= size) return (size - scaled) / 2;

			return Math.min(0, Math.max(size - scaled, t));
		};

		return {
			k,
			tx: span(width, land.width, v.tx),
			ty: span(height, land.height, v.ty)
		};
	}

	function apply(v){

		Object.assign(view, clamp(v));

		world.setAttribute(
			"transform",
			`translate(${view.tx.toFixed(2)} ${view.ty.toFixed(2)}) scale(${view.k.toFixed(4)})`
		);

		place();
	}

	function stop(){

		if(animation) cancelAnimationFrame(animation);

		animation = null;
	}

	// Zoom on a log scale and move the centre in a straight line, so a
	// long zoom does not swing wide on the way in.
	function animateTo(target, duration){

		stop();

		target = clamp(target);

		if(reducedMotion || !duration){
			apply(target);
			return;
		}

		const from = { ...view };

		const centre = v => [
			(width / 2 - v.tx) / v.k,
			(height / 2 - v.ty) / v.k
		];

		const [ax, ay] = centre(from);
		const [bx, by] = centre(target);

		const begin = performance.now();

		const ease = t => t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;

		const frame = now => {

			const t = Math.min(1, (now - begin) / duration);
			const e = ease(t);

			const k = Math.exp(Math.log(from.k) + (Math.log(target.k) - Math.log(from.k)) * e);
			const cx = ax + (bx - ax) * e;
			const cy = ay + (by - ay) * e;

			apply({ k, tx: width / 2 - cx * k, ty: height / 2 - cy * k });

			animation = t < 1 ? requestAnimationFrame(frame) : null;
		};

		animation = requestAnimationFrame(frame);
	}

	function zoomAt(factor, sx, sy, duration){

		const k = Math.max(minZoom, Math.min(MAX_ZOOM, view.k * factor));
		const ratio = k / view.k;

		animateTo({
			k,
			tx: sx - (sx - view.tx) * ratio,
			ty: sy - (sy - view.ty) * ratio
		}, duration);
	}

	function home(duration){
		animateTo(fit(net.view.home), duration);
	}

	/* ---------- building ---------- */

	function el(name, attrs, parent){

		const node = document.createElementNS(NS, name);

		for(const key in attrs){
			node.setAttribute(key, attrs[key]);
		}

		if(parent) parent.appendChild(node);

		return node;
	}

	function compact(n){

		if(n >= 1e6) return `${+(n / 1e6).toFixed(1)}M`;
		if(n >= 1e3) return `${Math.round(n / 1e3)}K`;

		return String(n);
	}

	function escapeHTML(value){

		return String(value).replace(/[&<>"']/g, ch => ({
			"&": "&amp;",
			"<": "&lt;",
			">": "&gt;",
			'"': "&quot;",
			"'": "&#39;"
		}[ch]));
	}

	function tagsFor(network){

		// ECS only means something where there is an endpoint to ask.
		if(!network.endpoints.length){
			return `<span class="tag quiet">Supporting network</span>`;
		}

		const tags = [];

		tags.push(network.ecs
			? `<span class="tag warm"><i class="bi bi-lightning-charge-fill"></i> ECS on</span>`
			: `<span class="tag quiet">No subnet sent</span>`);

		const profiles = [...new Set(network.endpoints.map(e => e.profile))];

		profiles.forEach(profile => {
			tags.push(`<span class="tag">${escapeHTML(profile)}</span>`);
		});

		return tags.join("");
	}

	function buildLand(){

		// Graticule every five degrees, under the land.
		const graticule = el("g", { class: "map-grid" }, world);

		const [west, south, east, north] = land.bbox;

		for(let lon = Math.ceil(west / 5) * 5; lon <= east; lon += 5){

			const [x] = project(lon, 0);

			el("line", { x1: x, y1: 0, x2: x, y2: land.height }, graticule);
		}

		for(let lat = Math.ceil(south / 5) * 5; lat <= north; lat += 5){

			const [, y] = project(0, lat);

			el("line", { x1: 0, y1: y, x2: land.width, y2: y }, graticule);
		}

		const countries = el("g", { class: "map-countries" }, world);

		land.countries.forEach(country => {

			const path = el("path", {
				class: country.sea ? "map-land sea-land" : "map-land",
				d: country.d
			}, countries);

			const title = el("title", {}, path);

			title.textContent = country.name;
		});
	}

	function buildOverlay(){

		const serving = net.networks.filter(n => n.endpoints.length);

		// Each city is tied to its nearest networks that actually serve
		// endpoints. Measured on the map, which at these latitudes is
		// close enough to the ground.
		net.cities.forEach(city => {

			city.map = project(city.lon, city.lat);

			city.near = serving
				.map(n => ({ n, d: Math.hypot(n.map[0] - city.map[0], n.map[1] - city.map[1]) }))
				.sort((a, b) => a.d - b.d)
				.slice(0, NEAREST)
				.map(o => o.n);
		});

		const reachLayer = el("g", { class: "map-reaches" }, overlay);

		net.cities.forEach(city => {

			city.links = city.near.map(n => ({
				network: n,
				path: el("path", { class: n.ecs ? "map-reach warm" : "map-reach" }, reachLayer)
			}));
		});

		const cityLayer = el("g", { class: "map-cities" }, overlay);

		net.cities.forEach(city => {

			city.g = el("g", { class: "map-city" }, cityLayer);

			el("circle", { r: 3 }, city.g);

			// "side": "left" in network.json puts the name on the other side
			// of the dot, for the places where two names would collide.
			const left = city.side === "left";

			city.text = el("text", {
				x: left ? -8 : 8,
				y: 4,
				"text-anchor": left ? "end" : "start"
			}, city.g);

			city.text.textContent = city.name;
		});

		const leaderLayer = el("g", { class: "map-leaders" }, overlay);
		const nodeLayer = el("g", { class: "map-nodes" }, overlay);

		net.networks.forEach(network => {

			network.leader = el("line", { class: "map-leader" }, leaderLayer);

			const g = el("g", {
				class: network.ecs ? "map-node ecs" : "map-node",
				tabindex: 0,
				role: "button",
				"data-asn": network.asn,
				"aria-label": `AS${network.asn}, ${network.name}, ${network.place}. ` +
					(network.endpoints.length
						? `Serves ${network.endpoints.map(e => e.host).join(", ")}.`
						: "")
			}, nodeLayer);

			el("circle", { class: "halo", r: 14 }, g);
			el("circle", { class: "hit", r: 16 }, g);
			el("circle", { class: "core", r: 7 }, g);

			network.text = el("text", { x: 13, y: 4 }, g);
			network.text.textContent = `AS${network.asn}`;

			network.g = g;

			wireNode(network);
		});
	}

	/* ---------- placing the overlay ---------- */

	// Fan out nodes that would sit on top of each other. Single linkage:
	// anything within CLUSTER_PX of a member joins the cluster.
	function declutter(){

		// A phone shows the whole region in a third of the width, so
		// nodes need to be further apart before they count as separate.
		const reach = width < 560 ? CLUSTER_PX * 1.4 : CLUSTER_PX;

		const items = net.networks.map(n => ({ n, at: toScreen(n.map) }));
		const groups = [];

		items.forEach(item => {

			const home = groups.find(group =>
				group.some(other =>
					Math.hypot(other.at[0] - item.at[0], other.at[1] - item.at[1]) < reach
				)
			);

			home ? home.push(item) : groups.push([item]);
		});

		const labelWidth = n => n.textWidth = n.textWidth || n.text.getComputedTextLength();

		groups.forEach(group => {

			if(group.length === 1){

				const { n, at } = group[0];

				n.shown = at;

				// Labels go right unless that runs off the map.
				n.side = at[0] + 20 + labelWidth(n) > width ? "left" : "right";

				return;
			}

			// A short column beside where they are, ordered by latitude so
			// the fan keeps north at the top. Left by default, right when
			// the labels would fall off the edge of the map.
			const cx = group.reduce((s, i) => s + i.at[0], 0) / group.length;
			const cy = group.reduce((s, i) => s + i.at[1], 0) / group.length;
			const gap = 24;

			const widest = Math.max(...group.map(i => labelWidth(i.n)));
			const side = cx - 34 - 18 - widest < 4 ? "right" : "left";

			group
				.sort((a, b) => a.at[1] - b.at[1])
				.forEach((item, index) => {

					item.n.shown = [
						side === "left" ? cx - 34 : cx + 34,
						cy + (index - (group.length - 1) / 2) * gap
					];

					item.n.side = side;
				});
		});
	}

	function arc(a, b){

		// Bow every link the same way, a fifth of its length.
		const mx = (a[0] + b[0]) / 2;
		const my = (a[1] + b[1]) / 2;
		const dx = b[0] - a[0];
		const dy = b[1] - a[1];

		return `M${a[0].toFixed(1)} ${a[1].toFixed(1)}` +
			`Q${(mx - dy * .2).toFixed(1)} ${(my + dx * .2).toFixed(1)} ` +
			`${b[0].toFixed(1)} ${b[1].toFixed(1)}`;
	}

	function place(){

		if(!overlay) return;

		declutter();

		net.networks.forEach(network => {

			const [x, y] = network.shown;
			const [rx, ry] = toScreen(network.map);

			network.g.setAttribute("transform", `translate(${x.toFixed(1)} ${y.toFixed(1)})`);

			const left = network.side === "left";

			network.text.setAttribute("x", left ? -13 : 13);
			network.text.setAttribute("text-anchor", left ? "end" : "start");

			const apart = Math.hypot(x - rx, y - ry) > 1;

			network.leader.setAttribute("x1", rx.toFixed(1));
			network.leader.setAttribute("y1", ry.toFixed(1));
			network.leader.setAttribute("x2", x.toFixed(1));
			network.leader.setAttribute("y2", y.toFixed(1));
			network.leader.style.display = apart ? "" : "none";
		});

		// City names only once there is room for them, and never on top
		// of a network: the nodes are the point, the cities are scenery.
		const crowded = view.k < fit(net.view.home).k * .8;

		const taken = net.networks.flatMap(network => {

			const [x, y] = network.shown;
			const w = network.textWidth;
			const left = network.side === "left";

			return [
				[x - 10, y - 10, x + 10, y + 10],
				left ? [x - 15 - w, y - 9, x - 11, y + 6] : [x + 11, y - 9, x + 15 + w, y + 6]
			];
		});

		const overlaps = box => taken.some(t =>
			box[0] < t[2] && box[2] > t[0] && box[1] < t[3] && box[3] > t[1]
		);

		net.cities.forEach(city => {

			const at = toScreen(city.map);
			const [x, y] = at;

			city.g.setAttribute("transform", `translate(${x.toFixed(1)} ${y.toFixed(1)})`);

			// Measured while visible and kept: a hidden label measures zero.
			const w = city.textWidth = city.textWidth || city.text.getComputedTextLength();
			const left = city.side === "left";

			const dot = [x - 3, y - 3, x + 3, y + 3];
			const label = left ? [x - 10 - w, y - 8, x - 6, y + 6] : [x + 6, y - 8, x + 10 + w, y + 6];

			city.g.style.display = overlaps(dot) ? "none" : "";
			city.text.style.display = crowded || overlaps(label) ? "none" : "";

			city.links.forEach(link => {
				link.path.setAttribute("d", arc(link.network.shown, at));
			});
		});

		if(pinned) positionTip(pinned);
	}

	/* ---------- tooltip ---------- */

	function tipHTML(network){

		const hosts = network.endpoints.length
			? `<ul class="tip-hosts">${network.endpoints.map(e => `
				<li>
					<code>${escapeHTML(e.host)}</code>
					<span>${escapeHTML(e.profile)}${e.qpd ? ` &middot; ${compact(e.qpd)}/day` : ""}</span>
				</li>`).join("")}</ul>`
			: "";

		return `
			<div class="tip-asn">AS${network.asn}</div>
			<div class="tip-name">${escapeHTML(network.name)}</div>
			<div class="tip-place"><i class="bi bi-geo-alt"></i> ${escapeHTML(network.place)}</div>
			<div class="tip-tags">${tagsFor(network)}</div>
			${hosts}
			<div class="tip-place mt-2">${escapeHTML(network.notes || "")}</div>`;
	}

	function positionTip(network){

		const [x, y] = network.shown;
		const w = tip.offsetWidth;
		const h = tip.offsetHeight;

		let left = x + 22;
		let top = y - 24;

		if(left + w > width - 12) left = x - 22 - w;
		if(left < 12) left = Math.max(12, Math.min(width - w - 12, x - w / 2));

		top = Math.max(12, Math.min(height - h - 12, top));

		tip.style.left = `${left}px`;
		tip.style.top = `${top}px`;
	}

	function openTip(network){

		tip.innerHTML = tipHTML(network);
		tip.classList.add("is-open");

		positionTip(network);

		hot(network.asn, true);
	}

	function closeTip(){

		tip.classList.remove("is-open");

		pinned = null;

		hot(null, false);
	}

	function hot(asn, on){

		document.querySelectorAll(".map-node.is-hot, .net-card.is-hot")
			.forEach(node => node.classList.remove("is-hot"));

		if(!on) return;

		document.querySelectorAll(`[data-asn="${asn}"]`)
			.forEach(node => node.classList.add("is-hot"));
	}

	function wireNode(network){

		const g = network.g;

		g.addEventListener("pointerenter", () => { if(!pinned) openTip(network) });
		g.addEventListener("pointerleave", () => { if(!pinned) closeTip() });
		g.addEventListener("focus", () => openTip(network));
		g.addEventListener("blur", () => { if(pinned !== network) closeTip() });

		// A tap or click pins it, so it stays on a phone.
		g.addEventListener("click", event => {

			event.stopPropagation();

			if(pinned === network){
				closeTip();
				return;
			}

			pinned = network;

			openTip(network);
		});

		g.addEventListener("keydown", event => {

			if(event.key === "Enter" || event.key === " "){

				event.preventDefault();

				pinned = network;

				openTip(network);
			}
		});
	}

	/* ---------- cards ---------- */

	function buildCards(){

		if(!grid) return;

		const busiest = Math.max(1, ...net.networks.flatMap(n => n.endpoints.map(e => e.qpd || 0)));

		grid.innerHTML = net.networks.map(network => {

			const hosts = network.endpoints.length
				? `<ul class="net-hosts">${network.endpoints.map(e => `
					<li class="net-host">
						<div class="net-host-row">
							<code>${escapeHTML(e.host)}</code>
							<span class="net-host-qpd">${e.qpd ? `${compact(e.qpd)}/day` : ""}</span>
						</div>
						<div class="net-host-profile">${escapeHTML(e.profile)}</div>
						${e.qpd
							? `<div class="qpd-bar" title="${escapeHTML(e.host)}: about ${e.qpd.toLocaleString("en")} queries a day"><i style="width:${(e.qpd / busiest * 100).toFixed(1)}%"></i></div>`
							: ""}
					</li>`).join("")}</ul>`
				: `<div class="net-empty">${escapeHTML(network.notes || "")}</div>`;

			return `
				<article class="net-card" data-asn="${network.asn}">
					<div class="net-asn">
						<i class="legend-dot${network.ecs ? " warm" : ""}"></i>
						AS${network.asn}
					</div>
					<div class="net-name">${escapeHTML(network.name)}</div>
					<div class="net-place">${escapeHTML(network.place)}</div>
					<div class="net-tags">${tagsFor(network)}</div>
					${hosts}
					<a class="net-link" href="https://bgp.tools/as/${network.asn}" target="_blank" rel="noopener">
						bgp.tools <i class="bi bi-box-arrow-up-right"></i>
					</a>
				</article>`;
		}).join("");

		grid.querySelectorAll(".net-card").forEach(cardNode => {

			cardNode.addEventListener("pointerenter", () => {
				if(!pinned) hot(cardNode.dataset.asn, true);
			});

			cardNode.addEventListener("pointerleave", () => {
				if(!pinned) hot(null, false);
			});
		});
	}

	/* ---------- input ---------- */

	function wireInput(){

		let drag = null;

		svg.addEventListener("pointerdown", event => {

			if(event.button !== 0 || event.target.closest(".map-node")) return;

			stop();

			touched = true;

			drag = { id: event.pointerId, x: event.clientX, y: event.clientY, tx: view.tx, ty: view.ty };

			svg.setPointerCapture(event.pointerId);
			svg.classList.add("is-dragging");
		});

		svg.addEventListener("pointermove", event => {

			if(!drag || drag.id !== event.pointerId) return;

			apply({
				k: view.k,
				tx: drag.tx + event.clientX - drag.x,
				ty: drag.ty + event.clientY - drag.y
			});
		});

		const release = event => {

			if(!drag || drag.id !== event.pointerId) return;

			drag = null;

			svg.classList.remove("is-dragging");
		};

		svg.addEventListener("pointerup", release);
		svg.addEventListener("pointercancel", release);

		svg.addEventListener("dblclick", event => {

			const box = svg.getBoundingClientRect();

			touched = true;

			zoomAt(1.8, event.clientX - box.left, event.clientY - box.top, 380);
		});

		const hint = card.querySelector(".map-hint");
		let hintTimer;

		svg.addEventListener("wheel", event => {

			if(!(event.ctrlKey || event.metaKey)){

				// Leave the page scrolling, but say how it is done.
				if(hint){

					hint.classList.add("is-loud");

					clearTimeout(hintTimer);

					hintTimer = setTimeout(() => hint.classList.remove("is-loud"), 1200);
				}

				return;
			}

			event.preventDefault();

			stop();

			touched = true;

			const box = svg.getBoundingClientRect();

			zoomAt(Math.exp(-event.deltaY * .0025), event.clientX - box.left, event.clientY - box.top, 0);

		}, { passive: false });

		card.querySelectorAll("[data-zoom]").forEach(button => {

			button.addEventListener("click", () => {

				touched = true;

				const action = button.dataset.zoom;

				if(action === "home") home(700);
				if(action === "in") zoomAt(1.6, width / 2, height / 2, 380);
				if(action === "out") zoomAt(1 / 1.6, width / 2, height / 2, 380);
			});
		});

		card.addEventListener("click", event => {
			if(!event.target.closest(".map-node")) closeTip();
		});

		document.addEventListener("keydown", event => {
			if(event.key === "Escape" && tip.classList.contains("is-open")) closeTip();
		});
	}

	function measure(){

		width = card.clientWidth;
		height = card.clientHeight;

		svg.setAttribute("viewBox", `0 0 ${width} ${height}`);

		// The furthest out you may go is the whole of the data.
		minZoom = Math.min(width / land.width, height / land.height);
	}

	function watchSize(){

		if(!("ResizeObserver" in window)) return;

		let timer;

		new ResizeObserver(() => {

			clearTimeout(timer);

			timer = setTimeout(() => {

				if(card.clientWidth === width && card.clientHeight === height) return;

				// Keep whatever was in the middle in the middle.
				const cx = (width / 2 - view.tx) / view.k;
				const cy = (height / 2 - view.ty) / view.k;

				measure();

				if(touched){
					apply({ k: view.k, tx: width / 2 - cx * view.k, ty: height / 2 - cy * view.k });
				}
				else{
					apply(fit(net.view.home));
				}

			}, 120);

		}).observe(card);
	}

	// Start wide, then settle on the region the first time the map is
	// actually looked at.
	function intro(){

		if(reducedMotion || !("IntersectionObserver" in window)){
			apply(fit(net.view.home));
			return;
		}

		apply(fit(net.view.intro));

		const io = new IntersectionObserver(entries => {

			entries.forEach(entry => {

				if(!entry.isIntersecting) return;

				io.disconnect();

				if(!touched) setTimeout(() => home(1700), 200);
			});

		}, { threshold: .35 });

		io.observe(card);
	}

	function pauseOffscreen(){

		if(!("IntersectionObserver" in window)) return;

		new IntersectionObserver(entries => {

			entries.forEach(entry =>
				card.classList.toggle("is-paused", !entry.isIntersecting)
			);

		}).observe(card);
	}

	/* ---------- start ---------- */

	function fail(err){

		console.error("Network map could not be drawn", err);

		const note = document.createElement("div");

		note.className = "map-fallback";
		note.textContent = "The map could not be loaded. The networks are listed in the footer.";

		card.appendChild(note);
	}

	async function start(){

		try{

			const [landResponse, netResponse] = await Promise.all([
				fetch("img/sea-map.json?hash=11635a40"),
				fetch("network.json?hash=e5c54b07", { cache: "no-cache" })
			]);

			if(!landResponse.ok) throw new Error(`sea-map.json responded ${landResponse.status}`);
			if(!netResponse.ok) throw new Error(`network.json responded ${netResponse.status}`);

			land = await landResponse.json();
			net = await netResponse.json();
		}
		catch(err){
			fail(err);
			return;
		}

		net.networks.forEach(network => {
			network.endpoints = network.endpoints || [];
			network.map = project(network.lon, network.lat);
		});

		svg = el("svg", {
			class: "map-svg",
			role: "group",
			"aria-label": "Map of the ΕΛΠΙΣ DNS networks in South East Asia"
		});

		world = el("g", { class: "map-world" }, svg);
		overlay = el("g", { class: "map-overlay" }, svg);

		card.prepend(svg);

		tip = document.getElementById("map-tip");

		buildLand();
		buildOverlay();
		buildCards();

		measure();
		intro();

		wireInput();
		watchSize();
		pauseOffscreen();

		card.querySelectorAll(".map-controls, .map-hint")
			.forEach(node => node.hidden = false);
	}

	start();

})();
